# Generated by Django 2.2.4 on 2020-08-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, db_column='First Name', max_length=100, null=True)),
                ('lastname', models.CharField(blank=True, db_column='Last Name', max_length=100, null=True)),
                ('city', models.CharField(blank=True, db_column='city', max_length=100, null=True)),
                ('mobile', models.CharField(blank=True, db_column='Mobile', max_length=20, null=True)),
                ('address', models.TextField(blank=True, db_column='Address', max_length=250, null=True)),
            ],
            options={
                'db_table': 'Post Detail',
            },
        ),
    ]
